### Test GET all flowers
GET http://localhost:8080/api/flowers
Accept: application/json

### Test POST new flower
POST http://localhost:8080/api/flowers
Content-Type: application/json

{
  "name": "Rose",
  "color": "Red",
  "price": 15.99,
  "available": true
}