### Test GET all users
GET http://localhost:8080/api/appusers
Accept: application/json

### Test POST to add a new user
POST http://localhost:8080/api/appusers
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "dob": "1990-05-14"
}